[bumpver]
current_version = "v0.0.1"
version_pattern = "vMAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "Bump version: {old_version} -> {new_version}"
tag_message = "{new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"vdc/version.py" = ['^__version__ = "{version}"$']
